project:
  type: book

book:
  title: "Kittenlab lecture notes"
  author: "Owen Lynch"
  date: "11/26/2022"
  chapters:
    - index.qmd
    - lecture1.qmd
    - lecture2.qmd
    - lecture3.qmd
    - lecture4.qmd
    - lecture5.qmd
    - lecture6.qmd
    - lecture7.qmd
    - lecture8.qmd
    - lecture9.qmd
    - lecture10.qmd
    - lecture11.qmd
    - references.qmd

bibliography: references.bib

execute:
  echo: true
  output: false

format:
  html:
    theme: cosmo
    css: main.css
    html-math-method: katex
    filters:
      - tikz.lua

from: markdown+tex_math_single_backslash
